uclouvain/osis-partnership

.travis.yml
forms.py

I applied the solution I exposed in [this post](https://stackoverflow.com/questions/51948640/using-limit-choices-to-on-a-fk-causes-multipleobjectsreturned-error-on-model) .

MultipleObjectsReturned fix

---

forms.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
templates/partnerships/partnerships_list.html
views.py

Fix partnerships filters

---

models.py
tests/test_partnership_update_view.py
views.py

There were errors when submissing partnership update form.

Fix partnership update

---

static/partnerships/partnerships.css
templates/partnerships/financings/financing_list.html

Changed financings forms front from collapse to tabs.

Financing list page form front.

---

management/commands/initialize_partner_type.py

À tester avec les données de prod avant de merge.

[OP-247] added command to initialize partner_type

---

tests/test_financings_export.py
tests/test_financings_import.py
tests/test_financings_list.py
tests/test_partner_create_view.py
tests/test_partner_detail_view.py
tests/test_partner_entity_views.py
tests/test_partner_media_views.py
tests/test_partner_update_view.py
tests/test_partners_list_view.py
tests/test_partnership_agreements_views.py
tests/test_partnership_contacts_views.py
tests/test_partnership_create_view.py
tests/test_partnership_detail_view.py
tests/test_partnership_update_view.py
tests/test_partnerships_list_view.py
tests/test_ucl_management_entity_create_view.py
tests/test_ucl_management_entity_delete_view.py
tests/test_ucl_management_entity_list_view.py
tests/test_ucl_management_entity_update_view.py
views.py

[OP-267] Accès aux views non protégé par des permissions

---

filter.py
tests/views/partnership/test_partnerships_list_view.py

J'ai remis la logique qui a été perdue dans le refactoring https://github.com/uclouvain/osis-partnership/blob/17c9e2e57be673f7a30733cd53a9a4dbaa41ea9c/views.py#L726-L772

OP-407 Put back multiple ordering logic in filters

---

api/serializers/configuration.py
api/serializers/partnership.py
api/views/configuration.py
filter.py
forms/partnership/filter.py
templates/partnerships/partnership/partnership_list.html
tests/api/test_api_configuration.py
tests/views/autocomplete/test_autocomplete_ucl_entity.py
tests/views/autocomplete/test_autocomplete_year_offers.py
tests/views/partnership/test_partnerships_list_view.py
urls.py
views/autocomplete/faculty.py
views/autocomplete/partner.py
views/autocomplete/partnership.py
views/autocomplete/ucl_university.py

cf https://jira.sgsi.ucl.ac.be/browse/OP-414?focusedCommentId=18408&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-18408

Hotfix autocompletes search

---

fixtures/funding_program.json
fixtures/funding_source.json
fixtures/funding_type.json

To load fixtures (order matters) :
- ./manage.py loaddata partnership/fixtures/funding_source.json
- ./manage.py loaddata partnership/fixtures/funding_program.json
- ./manage.py loaddata partnership/fixtures/funding_type.json

Add funding dataset

---

locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
models/partnership/partnership.py
models/partnership/partnership_year.py
templates/partnerships/agreements/agreement_list.html
templates/partnerships/partnership/partnership_list.html
tests/__init__.py
tests/views/partnership/test_partnerships_list_view.py
urls.py
views/agreement/list.py
views/export.py
views/partnership/export.py
views/partnership/list.py

OP-437 Export yearly data

---

api/filters/partnership.py
api/serializers/configuration.py
api/views/configuration.py
tests/api/test_api_configuration.py

Related https://github.com/uclouvain/osis-partnership-client/pull/94

Allow offers field in search api

---

api/url_v1.py
api/views/partnerships.py
tests/api/test_api_partnerships.py

See also https://github.com/uclouvain/osis-partnership-client/pull/95

OP-448 Public excel export

---

management/commands/import_partner_address.py
models/partner/partner.py

Suite d'[OP-404](https://jira.sgsi.ucl.ac.be/browse/OP-404)

Import partner addresses

---

api/url_v1.py
api/views/partnerships.py

https://github.com/uclouvain/osis-partnership-client/pull/95

OP-448 Add proxy to get export url

---

api/serializers/agreement.py
api/serializers/partnership.py
api/views/partnerships.py
models/partnership/partnership.py
static/partnerships/list.js
templates/partnerships/partnership/partnership_detail.html
templates/partnerships/partnership/partnership_list.html
tests/test_utils.py
utils.py
views/partnership/export.py

Comprend les modifications pour fix de bug :
- OP-456 
- OP-458 
- OP-459 
- OP-464 
- OP-467

Recette Bart

---

forms/partnership/configuration.py
models/partnership/configuration.py
tests/forms/test_configuration_form.py
tests/views/partnership/test_partnership_agreements_views.py
tests/views/partnership/test_partnership_course.py
tests/views/partnership/test_partnership_create_view.py
tests/views/partnership/test_partnership_doctorate.py
tests/views/partnership/test_partnership_general.py
tests/views/partnership/test_partnership_project.py
tests/views/test_configuration.py
views/partnership/list.py

Hotfix for https://jira.sgsi.ucl.ac.be/browse/OP-474

Hotfix OP-474 Never ever use date.today().year

---

management/commands/import_partner_address.py

Most of it is refactoring for display purposes, the two fixes are highlighted in comments

Fix address changed detection and getting existing addresses

---

tests/views/partnership/test_partnership_agreements_views.py
views/agreement/media.py

https://jira.sgsi.ucl.ac.be/browse/OP-479

OP-479 Allow authenticated user to download agreement media

---

forms/partner/entity.py
tests/views/partner/test_partner_update_view.py
views/partner/mixins.py

https://jira.sgsi.ucl.ac.be/browse/OP-493

OP-493 Make partner city and country required

---

tests/views/partnership/test_partnership_agreements_views.py
views/agreement/mixins.py

https://jira.sgsi.ucl.ac.be/browse/OP-496

OP-496 Fix upload name of agreement file

---

__init__.py

https://jira.sgsi.ucl.ac.be/browse/OP-495

OP-495 Prevent sql params casting on subqueries

---

api/serializers/partner.py
schema.yml
tests/api/test_api_partners.py

- Set organization_identifier to not required for IntershipPartnerCreation

Fix intégration ESB MOBI

---

forms/partnership/partnership.py

OP-509: Permettre à un utilisateur de modifier le champ 'Entité Uclouvain' en édition

---

admin.py
filter.py
forms/partnership/filter.py
templates/partnerships/partnership/partnership_list.html

Pull request automatique de feature/OP-522 vers DEV

[feature/OP-522 => DEV] Ajout d_une coche pour _Inclure les entités subordonnées_ dans la recherche des partenariats pour les institutions partenaires
